# image: node:10.16.3

# cache:
#   paths:
#     - node_modules/

# variables:
#   GIT_STRATEGY: fetch
#   GIT_DEPTH: 10

# before_script:
#   - npm install
#   - npm install -g firebase-tools

# test:
#   stage: test
#   retry:
#     max: 2
#     when:
#       - runner_system_failure
#       - stuck_or_timeout_failure
#   script:
#     - npm run test

# deploy:
#   stage: deploy
#   retry:
#     max: 2
#     when: always
#   script:
#     - npm run build
#     - npm run bundlesize
#     - firebase use palashg7563-blog-d9d54 --token $FIREBASE_TOKEN
#     - firebase deploy --except functions -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID" --token $FIREBASE_TOKEN
#   only:
#     - master
